ConfiguracionCalendario As screen:

    Rectangle6 As rectangle:
        BorderColor: =RGBA(235, 176, 0, 1)
        Fill: =RGBA(255, 191, 0, 1)
        Width: =1366
        ZIndex: =1

    Label11 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =100
        Size: =40
        Text: ="Configuración Calendario"
        Width: =729
        X: =318
        ZIndex: =2

    Icon2 As icon.Undo:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.Undo
        OnSelect: =Back()
        X: =122
        Y: =18
        ZIndex: =3

    Label12 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =241
        Y: =311
        ZIndex: =4

    Label12_1 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =622
        Y: =311
        ZIndex: =5

    Label12_2 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana1"
        X: =1003
        Y: =287
        ZIndex: =6

    Label12_3 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Height: =44
        Size: =16
        Text: ="Fecha Fin"
        X: =241
        Y: =518
        ZIndex: =7

    Label12_4 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Fin"
        X: =622
        Y: =520
        ZIndex: =8

    Label12_5 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana2"
        X: =1003
        Y: =496
        ZIndex: =9

    Label12_6 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Verano"
        Width: =169
        X: =612
        Y: =175
        ZIndex: =10

    Label12_7 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Invierno"
        Width: =165
        X: =995
        Y: =175
        ZIndex: =11

    Label12_8 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =76
        Size: =20
        Text: |-
            ="Petición
            Vacaciones"
        Width: =175
        X: =228
        Y: =175
        ZIndex: =12

    DatePicker1 As datepicker:
        Width: =250
        X: =191
        Y: =365
        ZIndex: =13

    DatePicker1_1 As datepicker:
        Width: =250
        X: =191
        Y: =570
        ZIndex: =14

    DatePicker1_2 As datepicker:
        Width: =250
        X: =572
        Y: =365
        ZIndex: =15

    DatePicker1_3 As datepicker:
        Height: =44
        Width: =250
        X: =572
        Y: =570
        ZIndex: =16

    DatePicker1_4 As datepicker:
        Width: =250
        X: =953
        Y: =335
        ZIndex: =17

    DatePicker1_5 As datepicker:
        Width: =250
        X: =953
        Y: =408
        ZIndex: =18

    DatePicker1_6 As datepicker:
        Width: =250
        X: =953
        Y: =548
        ZIndex: =19

    DatePicker1_7 As datepicker:
        Width: =250
        X: =953
        Y: =614
        ZIndex: =20

