ConfiguracionFestivos As screen:

    "GalleryFestivos As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver5.0'":
        '#CopilotOverlayLabel': ="Filtrada"
        DelayItemLoading: =true
        Fill: =RGBA(241, 244, 249, 0.7)
        Height: =668
        Items: |-
            =Sort(
                DiasFestivos,
                Fecha
            )
        Layout: =Layout.Vertical
        LoadingSpinner: =LoadingSpinner.Data
        TemplatePadding: =0
        TemplateSize: =90
        Width: =468
        Y: =100
        ZIndex: =2

        Title2 As label:
            FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
            Height: =38
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =20
            Text: =ThisItem.Motivo
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.TemplateWidth - 86
            X: =16
            Y: =15
            ZIndex: =1

        Subtitle2 As label:
            FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
            Height: =28
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =16
            Text: =ThisItem.Fecha
            VerticalAlign: =VerticalAlign.Top
            Width: =382
            X: =16
            Y: =Title2.Y + Title2.Height
            ZIndex: =2

        Separator3 As rectangle:
            Height: =8
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - Self.Height
            ZIndex: =4

        Rectangle12 As rectangle:
            Height: =Parent.TemplateHeight - Separator3.Height
            OnSelect: =Select(Parent)
            Visible: =ThisItem.IsSelected
            Width: =4
            ZIndex: =5

        Icon4 As icon.Trash:
            Color: =RGBA(255, 0, 0, 1)
            Height: =52
            Icon: =Icon.Trash
            OnSelect: =Set(popupeliminarfestivo,true)
            Width: =51
            X: =398
            Y: =15
            ZIndex: =6

    Rectangle6_1 As rectangle:
        BorderColor: =RGBA(235, 176, 0, 1)
        Fill: =RGBA(255, 191, 0, 1)
        Width: =1366
        ZIndex: =3

    Label11_1 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =100
        Size: =40
        Text: ="Configuración Festivos"
        Width: =729
        X: =318
        ZIndex: =4

    VolverConfigFestivos As icon.Undo:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.Undo
        OnSelect: =Back()
        X: =122
        Y: =18
        ZIndex: =5

    txtMotivoFestivo As text:
        Default: =
        Height: =49
        HintText: ="Motivo"
        Width: =328
        X: =764
        Y: =365
        ZIndex: =7

    BtnAñadirFestivos As button:
        Fill: =RGBA(54, 176, 75, 1)
        OnSelect: |-
            =If(
                IsBlank(txtMotivoFestivo),
                Collect(
                    DiasFestivos,
                    {
                        Fecha: dpFestivos.SelectedDate,
                        Motivo: txtMotivoFestivo.Text
                    }
                )
                ,
                Notify(
                    "Debes especificar el motivo del día festivo",
                    NotificationType.Error,
                    2000
                )
            )
        Text: ="Añadir"
        X: =848
        Y: =548
        ZIndex: =8

    dpFestivos As datepicker:
        X: =764
        Y: =240
        ZIndex: =16

    PopupEliminarFestivos As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =16

        Rectangle3 As rectangle:
            Fill: =RGBA(0, 0, 0, 0.2)
            Height: =768
            Visible: =popupeliminarfestivo
            Width: =1366
            ZIndex: =9

        Rectangle4 As rectangle:
            Height: =362
            Visible: =popupeliminarfestivo
            Width: =575
            X: =395
            Y: =203
            ZIndex: =10

        Icon5 As icon.Information:
            Color: =RGBA(255, 0, 0, 1)
            Fill: =RGBA(255, 255, 0, 1)
            Icon: =Icon.Information
            Visible: =popupeliminarfestivo
            X: =407
            Y: =216
            ZIndex: =11

        Label1 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            FontWeight: =FontWeight.Semibold
            Height: =101
            Size: =18
            Text: ="¿Quieres eliminar este día festivo?"
            Visible: =popupeliminarfestivo
            Width: =259
            X: =553
            Y: =251
            ZIndex: =12

        btnCancelarEliminarFestivo As button:
            Fill: =RGBA(255, 0, 0, 1)
            OnSelect: =Set(popupeliminarfestivo,false)
            Text: ="Cancelar"
            Visible: =popupeliminarfestivo
            X: =491
            Y: =461
            ZIndex: =13

        btnAceptarEliminarFestivo As button:
            Fill: =RGBA(54, 176, 75, 1)
            OnSelect: |-
                =Remove(
                    DiasFestivos,
                    GalleryFestivos.Selected
                )
                ;
                Set(popupeliminarfestivo,false)
            Text: ="Aceptar"
            Visible: =popupeliminarfestivo
            X: =721
            Y: =461
            ZIndex: =14

        Label2 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            FontWeight: =FontWeight.Semibold
            Height: =54
            Size: =14
            Text: =GalleryFestivos.Selected.Motivo&"     "&GalleryFestivos.Selected.Fecha
            Visible: =popupeliminarfestivo
            Width: =432
            X: =466
            Y: =365
            ZIndex: =15

