ConfiguracionCalendario As screen:

    Rectangle7_2 As rectangle:
        Fill: =RGBA(255, 234, 224, 1)
        Height: =667
        Width: =455
        X: =455
        Y: =100
        ZIndex: =1

    Rectangle7_1 As rectangle:
        Fill: =RGBA(241, 244, 249, 1)
        Height: =667
        Width: =456
        X: =910
        Y: =101
        ZIndex: =2

    Rectangle7 As rectangle:
        Fill: =RGBA(232, 244, 217, 1)
        Height: =667
        Width: =456
        Y: =100
        ZIndex: =3

    Rectangle6 As rectangle:
        BorderColor: =RGBA(235, 176, 0, 1)
        Fill: =RGBA(255, 191, 0, 1)
        Width: =1366
        ZIndex: =4

    Label11 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =100
        Size: =40
        Text: ="Configuración Calendario"
        Width: =729
        X: =318
        ZIndex: =5

    Icon2 As icon.Undo:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.Undo
        OnSelect: =Navigate(Calendario)
        X: =122
        Y: =18
        ZIndex: =6

    Label12 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =153
        Y: =283
        ZIndex: =7

    Label12_1 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =608
        Y: =283
        ZIndex: =8

    Label12_2 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana1"
        X: =1068
        Y: =259
        ZIndex: =9

    Label12_3 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Height: =44
        Size: =16
        Text: ="Fecha Fin"
        X: =153
        Y: =490
        ZIndex: =10

    Label12_4 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Fin"
        X: =608
        Y: =492
        ZIndex: =11

    Label12_5 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana2"
        X: =1068
        Y: =468
        ZIndex: =12

    Label12_6 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Verano"
        Width: =169
        X: =598
        Y: =147
        ZIndex: =13

    Label12_7 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Invierno"
        Width: =165
        X: =1060
        Y: =147
        ZIndex: =14

    Label12_8 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =76
        Size: =20
        Text: |-
            ="Petición
            Vacaciones"
        Width: =175
        X: =140
        Y: =147
        ZIndex: =15

    dp_InicioPeticion As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).InicioPeticion
        Width: =250
        X: =103
        Y: =337
        ZIndex: =16

    dp_FinPeticion As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).FinPeticion
        Width: =250
        X: =103
        Y: =542
        ZIndex: =17

    dp_InicioVerano As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).InicioVerano
        Width: =250
        X: =558
        Y: =337
        ZIndex: =18

    dp_Fin_Verano As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).FinVerano
        Height: =44
        Width: =250
        X: =558
        Y: =542
        ZIndex: =19

    dp_InicioInvierno As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).InicioInvierno
        Width: =250
        X: =1018
        Y: =307
        ZIndex: =20

    dp_FinInvierno As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).FinInvierno
        Width: =250
        X: =1018
        Y: =380
        ZIndex: =21

    dp_InicioInvierno2 As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).InicioInvierno2
        Width: =250
        X: =1018
        Y: =520
        ZIndex: =22

    dp_FinInvierno2 As datepicker:
        DefaultDate: |-
            =First(
                Filter(
                    ConfiguracionCalendario_1,
                    Año=Text(Year(Today()))
                )
            ).FinInvierno2
        Width: =250
        X: =1018
        Y: =586
        ZIndex: =23

    Button2_2 As button:
        OnSelect: |-
            =If(IsEmpty(Filter(ConfiguracionCalendario_1,Año=Text(Today(),"yyyy"))),
                Collect(
                    ConfiguracionCalendario_1,
                    {
                        Año: Text(Today(),"yyyy"),
                        InicioPeticion: dp_InicioPeticion.SelectedDate,
                        FinPeticion: dp_FinPeticion.SelectedDate,
                        InicioVerano: dp_InicioVerano.SelectedDate,
                        FinVerano: dp_Fin_Verano.SelectedDate,
                        InicioInvierno: dp_InicioInvierno.SelectedDate,
                        FinInvierno: dp_FinInvierno.SelectedDate,
                        InicioInvierno2: dp_InicioInvierno2.SelectedDate,
                        FinInvierno2: dp_FinInvierno2.SelectedDate
                    }
                ),
                Patch(
                    ConfiguracionCalendario_1,
                    LookUp(ConfiguracionCalendario_1,Año=Text(Today(),"yyyy")),
                    {
                       InicioPeticion: dp_InicioPeticion.SelectedDate,
                        FinPeticion: dp_FinPeticion.SelectedDate,
                        InicioVerano: dp_InicioVerano.SelectedDate,
                        FinVerano: dp_Fin_Verano.SelectedDate,
                        InicioInvierno: dp_InicioInvierno.SelectedDate,
                        FinInvierno: dp_FinInvierno.SelectedDate,
                        InicioInvierno2: dp_InicioInvierno2.SelectedDate,
                        FinInvierno2: dp_FinInvierno2.SelectedDate 
                    }
                )
            )
        Text: ="Confirmar"
        X: =603
        Y: =676
        ZIndex: =26

    Button2 As button:
        Fill: =RGBA(255, 166, 230, 1)
        OnSelect: =Navigate(ConfiguracionFestivos)
        Text: ="Festivos"
        X: =1161
        Y: =30
        ZIndex: =27

