ConfiguracionCalendario As screen:

    Rectangle6 As rectangle:
        BorderColor: =RGBA(235, 176, 0, 1)
        Fill: =RGBA(255, 191, 0, 1)
        Width: =1366
        ZIndex: =1

    Label11 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =100
        Size: =40
        Text: ="Configuración Calendario"
        Width: =729
        X: =318
        ZIndex: =2

    Icon2 As icon.Undo:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.Undo
        OnSelect: =Back()
        X: =122
        Y: =18
        ZIndex: =3

    Label12 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =227
        Y: =283
        ZIndex: =4

    Label12_1 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Inicio"
        X: =608
        Y: =283
        ZIndex: =5

    Label12_2 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana1"
        X: =989
        Y: =259
        ZIndex: =6

    Label12_3 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Height: =44
        Size: =16
        Text: ="Fecha Fin"
        X: =227
        Y: =490
        ZIndex: =7

    Label12_4 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Fecha Fin"
        X: =608
        Y: =492
        ZIndex: =8

    Label12_5 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Size: =16
        Text: ="Semana2"
        X: =989
        Y: =468
        ZIndex: =9

    Label12_6 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Verano"
        Width: =169
        X: =598
        Y: =147
        ZIndex: =10

    Label12_7 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =65
        Size: =20
        Text: |-
            ="Vacaciones
            Invierno"
        Width: =165
        X: =981
        Y: =147
        ZIndex: =11

    Label12_8 As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Bold
        Height: =76
        Size: =20
        Text: |-
            ="Petición
            Vacaciones"
        Width: =175
        X: =214
        Y: =147
        ZIndex: =12

    DatePicker1 As datepicker:
        Width: =250
        X: =177
        Y: =337
        ZIndex: =13

    DatePicker1_1 As datepicker:
        Width: =250
        X: =177
        Y: =542
        ZIndex: =14

    DatePicker1_2 As datepicker:
        Width: =250
        X: =558
        Y: =337
        ZIndex: =15

    DatePicker1_3 As datepicker:
        Height: =44
        Width: =250
        X: =558
        Y: =542
        ZIndex: =16

    DatePicker1_4 As datepicker:
        Width: =250
        X: =939
        Y: =307
        ZIndex: =17

    DatePicker1_5 As datepicker:
        Width: =250
        X: =939
        Y: =380
        ZIndex: =18

    DatePicker1_6 As datepicker:
        Width: =250
        X: =939
        Y: =520
        ZIndex: =19

    DatePicker1_7 As datepicker:
        Width: =250
        X: =939
        Y: =586
        ZIndex: =20

    Button2 As button:
        Text: ="Confirmar"
        X: =217
        Y: =676
        ZIndex: =21

    Button2_1 As button:
        Text: ="Confirmar"
        X: =984
        Y: =676
        ZIndex: =22

    Button2_2 As button:
        Text: ="Confirmar"
        X: =603
        Y: =676
        ZIndex: =23

